### ISSUE TITLE
About the simple example code in the readme

### ISSUE THREAD

**Issue by chinchihwork** [zama-ai/tfhe-rs#702] opened 2023-11-21 01:06 UTC
**Describe the bug**
The simple example code won't run on my OS(windows x86_64)

**To Reproduce**
Steps to reproduce the behaviour
1. Copy the example code in the README to IDE
2. cargo run --release on terminal 
3. bug report

**Evidence**
![image](https://github.com/zama-ai/tfhe-rs/assets/142082125/7c563e30-bbe7-4487-9ccc-f84ee7740f62)
![image](https://github.com/zama-ai/tfhe-rs/assets/142082125/ec94f4d4-c0b6-4693-bc79-a2d06e731436)
![image](https://github.com/zama-ai/tfhe-rs/assets/142082125/b660bb1f-f7d1-4c02-83c7-d612bdf0aba3)

**Configuration(please complete the following information):**
 - OS: Microsoft windows 11

**Comment by IceTDrinker** [comment] 2023-11-21 06:36
hello @chinchihwork it’s not a bug it’s just that our main branch has evolved and it has breaking changes compared to 0.4 which was the last version published. Can you try with the code from main ?

Otherwise the function call change you did is the correct one to get it working again.

If you check https://github.com/zama-ai/tfhe-rs/tree/release/0.4.x you will see the readme has the function call you expect. Keeping this issue open for now as we will want to see how to handle this

**Comment by chinchihwork** [comment] 2023-11-22 04:20
hello @IceTDrinker, thanks for replying.

I cloned the code from main branch to my .cargo/registry today but the code on README still couldn't run at first. Then I realised I didn't change the dependency setting in my cargo.toml. 

After I change the dependency setting to:

```toml
[dependencies]
tfhe = { git = "https://github.com/zama-ai/tfhe-rs.git", version = "0.5.0" , features = ["boolean", "shortint", "integer", "x86_64"] }
```
It works fine. Thanks for answering!

Also, since I am a beginner learning rust, I was wondering if I config the dependency to github repository, I won't download anything from remote to my local .cargo/registry right? Because  I don't see any change in my .cargo/registry after I change the dependency.

Thanks for helping out!

**Comment by IceTDrinker** [comment] 2023-11-22 09:18
Looks like cargo clones repositories in ls ~/.cargo/git, not quite sure how it is organized in there ! One thing to be wary of is that if we push new stuff to main it will only update the github repository when you do a cargo update.

If we have answered your questions feel free to close the issue 🙂

**Closed** 2023-11-22 09:23 UTC
Labels: bug, documentation
