### ISSUE TITLE
Remainder doesn't seem to work

### ISSUE THREAD

**Issue by JoseSK999** [zama-ai/tfhe-rs#509] opened 2023-08-28 16:10 UTC
**Describe the bug**
The remainder operation doesn't seem to work. When reducing a 64 byte number modulo a 32 bytes one, the 32 Most Significant bytes should be 0, but they aren't.

**To Reproduce**
The following program panics at the assertion.
```rust
use std::array;
use tfhe::integer::{gen_keys_radix, U256, U512};
use tfhe::shortint::parameters::PARAM_MESSAGE_2_CARRY_2;
use rand::{Rng, thread_rng};

const N_BYTES: [u8; 64] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 254, 186, 174, 220, 230, 175, 72, 160, 59, 191, 210, 94, 140, 208, 54, 65, 65];

fn main() {
    let (ck, sk) = gen_keys_radix(PARAM_MESSAGE_2_CARRY_2, 256);

    let mut random = thread_rng();
    let value_bytes = array::from_fn::<u8, 64, _>(|_| random.gen());

    let mut value = U512::from(0u8);
    value.copy_from_be_byte_slice(&value_bytes);
    let mut value_enc = ck.encrypt(value);

    let mut n = U256::from(0u8);
    n.copy_from_be_byte_slice(&N_BYTES[32..]);

    sk.smart_scalar_rem_assign_parallelized(&mut value_enc, n);

    let dec: U512 = ck.decrypt(&value_enc);
    let mut result_bytes = [0u8; 64];
    dec.copy_to_be_byte_slice(&mut result_bytes);
    // The 32 Most Significant bytes should be 0, as it has been reduced
    println!("{:?}", result_bytes);

    let mut n = U512::from(0u8);
    n.copy_from_be_byte_slice(&N_BYTES);
    assert_eq!(dec, value % n);
}
```

**Configuration:**
 - OS: MacOS BigSur 11.7.6

**Comment by IceTDrinker** [comment] 2023-08-28 16:15
hello @JoseSK999 we are missing the imports in your snippet can you add them please ? :)

**Comment by JoseSK999** [comment] 2023-08-28 16:19
> hello @JoseSK999 we are missing the imports in your snippet can you add them please ? :)

Sorry, I updated it!

**Comment by IceTDrinker** [comment] 2023-08-28 16:20
all good, did you observe the bug for smaller types as well ?

**Comment by IceTDrinker** [comment] 2023-08-28 16:21
which version of TFHE-rs are you using ? I seem to get an issue with the u512 encryption

**Comment by JoseSK999** [comment] 2023-08-28 16:21
I haven’t tried it with small ones

**Comment by JoseSK999** [comment] 2023-08-28 16:23
> which version of TFHE-rs are you using ? I seem to get an issue with the u512 encryption

0.3.1 for x86_64-unix

**Comment by JoseSK999** [comment] 2023-08-28 16:49
I had the same problem in a M2 as well

**Comment by IceTDrinker** [comment] 2023-08-28 17:53
M2/M1 are likely working with little endian data, also u256/512 work with little endian can you try changin the be to le in you copy byte functions ?

**Comment by IceTDrinker** [comment] 2023-08-28 17:53
And integer ciphertexts are also stored in little endian so yeah

**Comment by IceTDrinker** [comment] 2023-08-29 08:33
apologies, the u64/u32 case is not working, made a mistake in my code and types were not mixed, we are investigating !

**Comment by tmontaigu** [comment] 2023-08-29 08:52
The problem is that the function requires the Scalar type to have at least has many bits as the ciphertext for it to work properly. But we are missing the assert on that.

using the 0.3.1 version you can't use a U512 as the scalar type for scalar division, however if you try with this branch https://github.com/zama-ai/tfhe-rs/pull/507 you will be able to use a U512 as the scalar, and see that it works as expected

**Comment by JoseSK999** [comment] 2023-08-29 14:47
Yes it works!

**Comment by tmontaigu** [comment] 2023-10-03 14:15
Closing as Div/Rem by U512 is now possible on main, and an assert is in place to cover the original problem

**Closed by tmontaigu** 2023-10-03 14:15 UTC
